version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    command: npm start

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    command: npm start
